server:
  servlet:
    context-path: /api/v0/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:${PORT}/medical_clinics?createDatabaseIfNotExist=true"
    username: ${USERNAME}
    password: ${PASSWORD}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true

user:
  account:
    defaultRole: PATIENT
    status: ACTIVE

admin:
  default:
    mail: admin@admin.com
    password: 1Ae#92cO.gK
    firstName: Admin
    lastName: Admin
    phone:

app:
  jwt:
    secret: AAWEEE2VjZHNhLXNoYTItbmlzdHAyNTYA7564AIbmlzdHAyNTYAGHtwBN5lf15QnqbwSxIS5HSPWGmGqRcONU4Nn1swj6OBFC0SjnsRe2NSa0z1CK21j7VJu730X3T4G1RfJnugRyLJfs

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json