/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClinicShortInfo } from '../../models/clinic-short-info';

export interface GetAllClinics$Params {
}

export function getAllClinics(http: HttpClient, rootUrl: string, params?: GetAllClinics$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClinicShortInfo>>> {
  const rb = new RequestBuilder(rootUrl, getAllClinics.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ClinicShortInfo>>;
    })
  );
}

getAllClinics.PATH = '/clinics/';
