server:
  port: 8081
  servlet:
    context-path: /api/v0/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:${PORT}/medical_records?createDatabaseIfNotExist=true"
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  application:
    name: medical-records-notes
