/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccountInformation {
  email?: string;
  id: string;
  role?: 'PATIENT' | 'ADMIN' | 'PHYSICIAN';
  status?: 'ACTIVE' | 'INACTIVE' | 'BLOCKED';
}
