/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClinicShortInfo {
  address?: string;
  city?: string;
  id?: string;
  pictureUrl?: string;
}
