/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePatient {
  address?: string;
  city?: string;
  country: string;
  email?: string;
  firstName: string;
  identificationCode: string;
  lastName: string;
  phone?: string;
}
