/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DayAppointmentPublic {
  startTime?: string;
  status?: 'RESERVED' | 'FREE' | 'PASSED' | 'INACTIVE';
  timeslotId: string;
}
