/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NewDaySchedule {
  date: string;
  endTime: string;
  startTime: string;
  timeSlotInterval: number;
}
