/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NoteResponse {
  chiefComplaint?: string;
  clinicIdentificationNumber?: string;
  creationDate?: string;
  diagnosis?: string;
  diagnosisCode?: string;
  documentNumber?: string;
  examination?: string;
  medicalHistory?: string;
  medicationAndRecommendations?: string;
  patientFullAddress?: string;
  patientIdentificationCode?: string;
  patientName?: string;
  physicianIdentificationNumber?: string;
  physicianInfo?: string;
  testResults?: string;
}
