/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PatientInfo {
  address?: string;
  city?: string;
  country?: string;
  email?: string;
  firstName?: string;
  identificationCode?: string;
  lastName?: string;
  patientId?: string;
  phone?: string;
}
