/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PatientAppointment {
  address?: string;
  appointmentDate?: string;
  physician?: string;
  startTime?: string;
  timeslotId?: string;
}
