/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhysicianInfo {
  abbreviation?: string;
  description?: string;
  firstName?: string;
  lastName?: string;
  physicianId: string;
  pictureUrl?: string;
  specialty?: string;
  workplace?: string;
}
