/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhysicianEditRequest {
  abbreviation?: string;
  description?: string;
  email: string;
  firstName: string;
  lastName: string;
  pictureUrl?: string;
}
