/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DayAppointmentPublic } from '../models/day-appointment-public';
export interface PhysicianDaySchedulePublic {
  date?: string;
  schedule?: Array<DayAppointmentPublic>;
  scheduleId?: string;
}
