/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DayAppointmentPrivate } from '../models/day-appointment-private';
export interface PhysicianDaySchedulePrivate {
  date?: string;
  schedule?: Array<DayAppointmentPrivate>;
  scheduleId?: string;
}
