/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserAccountEditRequest {
  address?: string;
  city?: string;
  country?: string;
  email: string;
  firstName: string;
  id: string;
  lastName: string;
  newPassword?: string;
  oldPassword?: string;
  phone?: string;
}
