/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PatientInfo } from './patient-info';
export interface UserDataResponse {
  accountId: string;
  patientInfo: PatientInfo;
  role?: 'PATIENT' | 'ADMIN' | 'PHYSICIAN';
}
