/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatientInfo } from '../../models/patient-info';

export interface FindPatient$Params {
  phoneNumber?: string;
  email?: string;
}

export function findPatient(http: HttpClient, rootUrl: string, params?: FindPatient$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PatientInfo>>> {
  const rb = new RequestBuilder(rootUrl, findPatient.PATH, 'get');
  if (params) {
    rb.query('phoneNumber', params.phoneNumber, {});
    rb.query('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PatientInfo>>;
    })
  );
}

findPatient.PATH = '/patients/filter';
