/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatientInfo } from '../../models/patient-info';

export interface GetPatient$Params {
  patientId: string;
}

export function getPatient(http: HttpClient, rootUrl: string, params: GetPatient$Params, context?: HttpContext): Observable<StrictHttpResponse<PatientInfo>> {
  const rb = new RequestBuilder(rootUrl, getPatient.PATH, 'get');
  if (params) {
    rb.path('patientId', params.patientId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PatientInfo>;
    })
  );
}

getPatient.PATH = '/patients/patient/{patientId}';
