/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhysicianInfo } from '../../models/physician-info';

export interface GetPhysicianInfo$Params {
  physicianId: string;
}

export function getPhysicianInfo(http: HttpClient, rootUrl: string, params: GetPhysicianInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<PhysicianInfo>> {
  const rb = new RequestBuilder(rootUrl, getPhysicianInfo.PATH, 'get');
  if (params) {
    rb.path('physicianId', params.physicianId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhysicianInfo>;
    })
  );
}

getPhysicianInfo.PATH = '/physicians/physician/{physicianId}';
