/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhysicianDaySchedulePublic } from '../../models/physician-day-schedule-public';

export interface GetPublicPhysicianSchedules$Params {
  physicianId: string;
}

export function getPublicPhysicianSchedules(http: HttpClient, rootUrl: string, params: GetPublicPhysicianSchedules$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PhysicianDaySchedulePublic>>> {
  const rb = new RequestBuilder(rootUrl, getPublicPhysicianSchedules.PATH, 'get');
  if (params) {
    rb.query('physicianId', params.physicianId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PhysicianDaySchedulePublic>>;
    })
  );
}

getPublicPhysicianSchedules.PATH = '/schedules/';
