/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatientAppointment } from '../../models/patient-appointment';

export interface GetPatientAppointments$Params {
  patientId: string;
}

export function getPatientAppointments(http: HttpClient, rootUrl: string, params: GetPatientAppointments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PatientAppointment>>> {
  const rb = new RequestBuilder(rootUrl, getPatientAppointments.PATH, 'get');
  if (params) {
    rb.path('patientId', params.patientId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PatientAppointment>>;
    })
  );
}

getPatientAppointments.PATH = '/schedules/patient/{patientId}';
