/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type {AccountInformation} from './models/account-information';
export type {ClinicDetails} from './models/clinic-details';
export type {ClinicShortInfo} from './models/clinic-short-info';
export type {CreateEditClinicRequest} from './models/create-edit-clinic-request';
export type {CreatePatient} from './models/create-patient';
export type {CreatePhysician} from './models/create-physician';
export type {DayAppointmentPrivate} from './models/day-appointment-private';
export type {DayAppointmentPublic} from './models/day-appointment-public';
export type {ExceptionResponse} from './models/exception-response';
export type {LoginRequest} from './models/login-request';
export type {NewDaySchedule} from './models/new-day-schedule';
export type {NewNoteRequest} from './models/new-note-request';
export type {NoteResponse} from './models/note-response';
export type {PatientAppointment} from './models/patient-appointment';
export type {PatientInfo} from './models/patient-info';
export type {PhysicianDaySchedulePrivate} from './models/physician-day-schedule-private';
export type {PhysicianDaySchedulePublic} from './models/physician-day-schedule-public';
export type {PhysicianEditRequest} from './models/physician-edit-request';
export type {PhysicianInfo} from './models/physician-info';
export type {RegisterRequest} from './models/register-request';
export type {SpecialityDto} from './models/speciality-dto';
export type {UserAccountEditRequest} from './models/user-account-edit-request';
export type {UserDataResponse} from './models/user-data-response';
export type {WorkDayDto} from "./models/work-day-dto";
