/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AccountInformation } from './models/account-information';
export { ClinicDetails } from './models/clinic-details';
export { ClinicShortInfo } from './models/clinic-short-info';
export { CreateEditClinicRequest } from './models/create-edit-clinic-request';
export { CreatePatient } from './models/create-patient';
export { CreatePhysician } from './models/create-physician';
export { DayAppointmentPrivate } from './models/day-appointment-private';
export { DayAppointmentPublic } from './models/day-appointment-public';
export { ExceptionResponse } from './models/exception-response';
export { LoginRequest } from './models/login-request';
export { NewDaySchedule } from './models/new-day-schedule';
export { NewNoteRequest } from './models/new-note-request';
export { NoteResponse } from './models/note-response';
export { PatientAppointment } from './models/patient-appointment';
export { PatientInfo } from './models/patient-info';
export { PhysicianDaySchedulePrivate } from './models/physician-day-schedule-private';
export { PhysicianDaySchedulePublic } from './models/physician-day-schedule-public';
export { PhysicianEditRequest } from './models/physician-edit-request';
export { PhysicianInfo } from './models/physician-info';
export { RegisterRequest } from './models/register-request';
export { SpecialityDto } from './models/speciality-dto';
export { UserAccountEditRequest } from './models/user-account-edit-request';
export { UserDataResponse } from './models/user-data-response';
export { WorkDayDto } from './models/work-day-dto';
