/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UserAccountControllerService } from './services/user-account-controller.service';
export { PhysicianControllerService } from './services/physician-controller.service';
export { PatientControllerService } from './services/patient-controller.service';
export { ClinicControllerService } from './services/clinic-controller.service';
export { ScheduleControllerService } from './services/schedule-controller.service';
export { MedicalRecordControllerService } from './services/medical-record-controller.service';
export { AuthenticationControllerService } from './services/authentication-controller.service';
