/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NoteResponse } from '../../models/note-response';

export interface GetPhysicianNotes$Params {
  accountId: string;
}

export function getPhysicianNotes(http: HttpClient, rootUrl: string, params: GetPhysicianNotes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NoteResponse>>> {
  const rb = new RequestBuilder(rootUrl, getPhysicianNotes.PATH, 'get');
  if (params) {
    rb.path('accountId', params.accountId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NoteResponse>>;
    })
  );
}

getPhysicianNotes.PATH = '/medical-records/physician/{accountId}';
