/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountInformation } from '../../models/account-information';

export interface GetAllUsersAccounts$Params {
}

export function getAllUsersAccounts(http: HttpClient, rootUrl: string, params?: GetAllUsersAccounts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AccountInformation>>> {
  const rb = new RequestBuilder(rootUrl, getAllUsersAccounts.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AccountInformation>>;
    })
  );
}

getAllUsersAccounts.PATH = '/users/';
